package com.example.ui

object NirvanaLocal {
    private val fa = mapOf(
        "app_title" to "نیروانا",
        "conversations" to "گفتگوها",
        "anti_spam" to "ضد تبلیغ",
        "settings" to "تنظیمات",
        "theme" to "تم برنامه",
        "font" to "فونت برنامه",
        "font_size" to "اندازه قلم",
        "spam_filter" to "فیلتر خودکار تبلیغات اسپم",
        "spam_rules" to "مدیریت قوانین فیلتر اسپم",
        "add_rule" to "افزودن قانون جدید فیلتر",
        "keyword" to "کلمه کلیدی تبلیغاتی",
        "sender" to "شماره فرستنده تبلیغاتی",
        "delete" to "حذف گفتگو",
        "block" to "مسدودسازی و انتقال به پوشه اسپم",
        "unblock" to "خروج از لیست اسپم",
        "type_msg" to "پیام خود را بنویسید...",
        "send" to "ارسال",
        "recipient" to "شماره گیرنده",
        "new_chat" to "پیام جدید",
        "start_chat" to "شروع گفتگو",
        "default_sms_prompt" to "نیروانا به عنوان پیام‌رسان پیش‌فرض تلفن شما تنظیم نشده است. جهت ارسال/دریافت پیام و تفکیک خودکار تبلیغات، آن را پیش‌فرض قرار دهید.",
        "set_default" to "تنظیم به عنوان پیام‌رسان پیش‌فرض",
        "no_permission" to "جهت نمایش پیامک‌ها و مخاطبین، لطفاً دسترسی‌های لازم را تایید کنید.",
        "grant_permission" to "اعطای دسترسی‌های لازم",
        "search_hint" to "جستجو در پیام‌ها...",
        "rule_pattern" to "متن کلمه کلیدی یا شماره",
        "theme_lavender" to "بنفش عرفانی نیروانا",
        "theme_oceanic" to "اقیانوسی آرامش‌بخش",
        "theme_royal" to "طلایی سلطنتی پرمیوم",
        "theme_light" to "کلاسیک روشن",
        "theme_dark" to "کلاسیک تاریک",
        "empty_threads" to "پیامی برای نمایش وجود ندارد.",
        "empty_spam" to "پوشه ضد تبلیغ شما کاملاً خالی است! تبلیغات مزاحم مهار شدند. 🛡️",
        "reset_rules" to "بازنشانی قوانین پیش‌فرض",
        "custom_rules_title" to "کلمات و خطوط فیلتر شده سفارشی شما",
        "anti_advertising_explanation" to "پیام‌های حاوی کلمات کلیدی فوق و پیش‌شماره‌های تبلیغاتی ایران (مثال: ۱۰۰۰، ۲۰۰۰ و ۵۰۰۰) به طور خودکار به پوشه ضد تبلیغ منتقل می‌شوند.",
        "add" to "افزودن",
        "promo_title" to "تبلیغ ویژه",
        "promo_action" to "مشاهده",
        "scheduled_title" to "پیام‌های زمان‌بندی شده",
        "schedule_at" to "زمان‌بندی ارسال ⏰",
        "sticker_title" to "استیکر سریع ✨",
        "search_advanced" to "فیلترهای پیشرفته ⚙️",
        "search_sender" to "فرستنده خاص",
        "search_keyword" to "کلمه کلیدی خاص",
        "search_date_range" to "محدوده زمانی",
        "date_all" to "همه پیام‌ها",
        "date_today" to "پیام‌های امروز",
        "date_week" to "پیام‌های این هفته",
        "date_month" to "پیام‌های این ماه",
        "sim_select" to "سیم‌کارت ارسال",
        "delay_prompt" to "تاخیر ارسال (ثانیه)",
        "admin_promo_settings" to "تنظیمات ادمین و تبلیغات بالای پیام‌رسان 🌐",
        "admin_settings" to "تنظیمات ادمین و تبلیغات",
        "promo_server_url" to "آدرس فایل متن تبلیغ روی هاست سی‌پنل (JSON)",
        "promo_fetch_btn" to "بروزرسانی از هاست سی‌پنل 🔄",
        "promo_text_label" to "متن بنر تبلیغاتی بالای پیام‌رسان",
        "promo_url_label" to "لینک مقصد کلیک تبلیغ (URL)",
        "promo_text" to "متن بنر تبلیغاتی بالای پیام‌رسان",
        "promo_link" to "لینک مقصد کلیک تبلیغ",
        "promo_fetch_url" to "آدرس فایل متن تبلیغ روی هاست سی‌پنل",
        "save" to "ذخیره تنظیمات ادمین",
        "fetch_cpanel" to "بروزرسانی تبلیغ از هاست سی‌پنل 🔄",
        "delayed_send_duration_title" to "تأخیر در ارسال پیام",
        "delayed_send_duration_desc" to "امکان مکث و لغو ارسال پیام تا حداکثر ۶ ثانیه",
        "hide_notification_content_title" to "عدم نمایش متن پیام در اعلان",
        "hide_notification_content_desc" to "نمایش کلمه «پیام جدید» در اعلان به جای متن پیامک اصلی",
        "delivery_report_title" to "گزارش تحویل پیامک",
        "delivery_report_desc" to "دریافت گزارش تحویل پیام‌های ارسالی و نمایش دو تیک در کنار پیامک‌های تحویل‌شده",
        "seconds_unit" to "ثانیه",
        "cancel_send" to "لغو ارسال",
        "sending_in" to "ارسال در %d ثانیه دیگر..."
    )

    private val en = mapOf(
        "app_title" to "Nirvana",
        "conversations" to "Conversations",
        "anti_spam" to "Anti-Spam",
        "settings" to "Settings",
        "theme" to "App Theme",
        "font" to "App Font",
        "font_size" to "Font Size",
        "spam_filter" to "Auto Filter Ad Spam",
        "spam_rules" to "Manage Filter Rules",
        "add_rule" to "Add New Filter Rule",
        "keyword" to "Ad Keyword",
        "sender" to "Ad Sender Suffix/Prefix",
        "delete" to "Delete Conversation",
        "block" to "Block & Mark as Spam",
        "unblock" to "Move to Main Folder (Ham)",
        "type_msg" to "Type your message...",
        "send" to "Send",
        "recipient" to "Recipient Number",
        "new_chat" to "New Message",
        "start_chat" to "Start Chat",
        "default_sms_prompt" to "Nirvana is not set as your default SMS app. To send/receive messages and automatically filter ad spam, please set it as default.",
        "set_default" to "Set as Default SMS App",
        "no_permission" to "To display messages and contacts, please grant the required permissions.",
        "grant_permission" to "Grant Required Permissions",
        "search_hint" to "Search messages...",
        "rule_pattern" to "Keyword text or phone prefix",
        "theme_lavender" to "Mystic Lavender Nirvana",
        "theme_oceanic" to "Calming Oceanic Teal",
        "theme_royal" to "Royal Gold Premium",
        "theme_light" to "Classic Light",
        "theme_dark" to "Classic Dark",
        "empty_threads" to "No conversations to display.",
        "empty_spam" to "Your Anti-Spam folder is fully clean! Ads successfully blockaded. 🛡️",
        "reset_rules" to "Reset to Default Rules",
        "custom_rules_title" to "Your Custom Blacklisted Keywords & Lines",
        "anti_advertising_explanation" to "Messages containing specified keywords or advertising prefixes in Iran (like 1000, 2000, 5000) are securely filtered into Anti-Spam.",
        "add" to "Add Rule",
        "promo_title" to "Special Ad",
        "promo_action" to "View",
        "scheduled_title" to "Scheduled Messages",
        "schedule_at" to "Schedule Message ⏰",
        "sticker_title" to "Stickers ✨",
        "search_advanced" to "Advanced Filters ⚙️",
        "search_sender" to "Specific Sender",
        "search_keyword" to "Specific Keyword",
        "search_date_range" to "Date Range",
        "date_all" to "All Messages",
        "date_today" to "Today's Messages",
        "date_week" to "This Week's Messages",
        "date_month" to "This Month's Messages",
        "sim_select" to "Send via SIM",
        "delay_prompt" to "Delay (seconds)",
        "admin_promo_settings" to "Admin & Top Banner Ad Settings 🌐",
        "admin_settings" to "Admin & Promo Settings",
        "promo_server_url" to "Remote JSON Ad Config URL (CPanel Host)",
        "promo_fetch_btn" to "Fetch Ad from CPanel Host 🔄",
        "promo_text_label" to "Top Banner Message Text",
        "promo_url_label" to "Banner Target Destination (URL)",
        "promo_text" to "Ad Banner Text",
        "promo_link" to "Ad Click URL",
        "promo_fetch_url" to "Ad Fetch Source (CPanel URL)",
        "save" to "Save Admin Settings",
        "fetch_cpanel" to "Fetch Ad from CPanel Host 🔄",
        "delayed_send_duration_title" to "Delayed Sending Duration",
        "delayed_send_duration_desc" to "Pause and cancel message sending up to 6 seconds",
        "hide_notification_content_title" to "Hide notification message text",
        "hide_notification_content_desc" to "Show 'New Message' word in notification instead of text body",
        "delivery_report_title" to "SMS Delivery Reports",
        "delivery_report_desc" to "Request delivery reports and show double checkmarks for delivered messages",
        "seconds_unit" to "seconds",
        "cancel_send" to "Cancel Send",
        "sending_in" to "Sending in %d seconds..."
    )

    fun get(key: String, lang: String): String {
        return if (lang == "fa") fa[key] ?: key else en[key] ?: key
    }
}
